create table if not exists feedback_snapshot (
  id bigint primary key auto_increment,
  snapshot_id varchar(64) not null,
  user_id varchar(64) not null,
  endpoint varchar(255) not null,
  algo_version varchar(64) null,
  field_path varchar(255) not null,
  displayed_as varchar(255) not null,
  original_value longtext null,
  corrected_value longtext null,
  reason text null,
  request_body longtext not null,
  response_body longtext not null,
  context longtext null,
  device_id varchar(128) null,
  firmware varchar(128) null,
  app_version varchar(128) null,
  env varchar(32) null,
  tester varchar(128) null,
  requested_at datetime null,
  submitted_at datetime null,
  review_status varchar(32) null,
  diagnosis varchar(32) null,
  review_remark text null,
  reviewed_by varchar(128) null,
  reviewed_at datetime null,
  create_time datetime not null,
  update_time datetime not null,
  unique key uk_feedback_snapshot_id (snapshot_id),
  key idx_feedback_user_id (user_id),
  key idx_feedback_endpoint (endpoint),
  key idx_feedback_field_path (field_path),
  key idx_feedback_env (env),
  key idx_feedback_create_time (create_time)
) engine=InnoDB default charset=utf8mb4;
